# Generated by Django 3.2.18 on 2023-02-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='camper',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='camping_memories',
        ),
    ]
