# Generated by Django 3.2.18 on 2023-02-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230220_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_oni8cm.jpg', upload_to='images/'),
        ),
    ]
